### ISSUE TITLE
Enhancing UserParameter Support

### ISSUE THREAD

**Issue by Wicaeed** [dj-wasabi/ansible-zabbix-agent#39]
Greetings,

I've been researching the various ways that one could go about adding custom user parameters to Zabbix. Right now I have a single UserParameter that I support which lets me do iostat monitoring across my hosts. I have people scrambling to get me to support more UserParamters to monitor things like Nginx, HAProxy and Memcache (to name a few).

Unfortunately, the iostat userparamter I'm using isn't quite as simple to implement as a single iostat.conf entry to the  configured 'agent_include' folder. The code I'm using ([https://github.com/jizhang/zabbix-templates/tree/master/iostat](url))  requires (in addition to the userparameter config file) a cron job to be created and run some shell scripts to run in order to compare the results of a file that is generated by the cron every minutes, and stored in the /tmp directory. 

Other userparameter extensions follow the same usage scenarios:

[https://github.com/anapsix/zabbix-haproxy]
- Executing shell scripts

[https://github.com/vicendominguez/nginx-zabbix-template]
- Executing python scripts

[https://github.com/alfss/zabbix-redis/tree/master/redis]
- Again calling scripts from UserParameter

I'm trying to think of some of the tasks that would need to be handled in Ansible to allow for this:
- Create the userparameter config file for the module, obviously
- Store any required scripts that the userparameter module uses. I would imagine that you would want to store these scripts in the Zabbix users home directory in a folder. I'm not sure were you would want to store the source of these scripts though, I would think another Git repository, but I'm not sure because I'm kind of an Ansible/Zabbix noob.
- Create cron entires in the Zabbix user crontab that the userparameter module would require.
- Create (touch) any tmp files that may be needed.
- UserParameter modules can be loaded by only the hosts that need it. 

Do you have any suggestions as to what might be a good path to accomplish this?

Thanks!

**Comment by dj-wasabi** [comment]
Hi @Wicaeed 

My definition of a role is the following: A role (Like for example: haproxy) should do everything that is needed for correct installation, configuration and correct working for the tool/purpose.

So in the case for haproxy, it should - if needed - create users/groups, install the haproxy application and configure the haproxy service correctly. Monitoring is part of this 'configuration' task. The role should not only be able to configure the '/etc/haproxy/haproxy.conf' file, but should also take care of the scripts/tasks for the monitoring of the haproxy application.

If the 'haproxy' role is executed against host a and not host b, all the monitoring related configuration can only be found on host a. If an error is made in the haproxy role regarding monitoring, only the servers which are affected by the ansible role has a problem. Everything else will just running smoothly (I hope ;-)).

The zabbix-agent role is only needed for installing and configuring the Zabbix Agent and if needed creating the host in the web interface (Via the Zabbix Server API). When the Zabbix Agent is also responsible for all the monitoring, the Ansible code will be complicated because you'll create a mixture of new properties combined with a lot of 'when' tasks.

If I where you, I would update the Ansible role for HAproxy, to make sure that the scripts that are part of the monitoring are installed, cron entries are created and placing the 'UserParameter' file into the configured `agent_include` directory. Same is for the role responsible for Redis. 

This is how I see that it should work and this is how I do it an my work, your mileage may vary, of course. :-)

**Comment by Wicaeed** [comment]
I think I see :)

Is there a proper way to make sure that if haproxy is installed, and you are installing the monitoring roles for haproxy, that Zabbix Agent role is already installed?

**Comment by dj-wasabi** [comment]
Yes, within the haproxy role there should be a directory named `meta` which contains a `main.yml`. This file has a property named `dependencies`. This is a list which can be used like this:

```
dependencies:
  - role: dj-wasabi.zabbix-agent
```
