### ISSUE TITLE
PSK in variable

### ISSUE THREAD

**Issue by ad-m** [dj-wasabi/ansible-zabbix-agent#83]
Hello,

There is no way to write-in PSK file content. I believe PSK file content should be writable based on variable. The variable content can be set generated eg. by lookup command.

Greetings,

**Comment by dj-wasabi** [comment]
Hi @ad-m 

Could you give me some more details on what you mean. It's not sure what you mean.

Thank you.

**Comment by ad-m** [comment]
@dj-wasabi , thank for you reply. The role support ``zabbix_agent_tlspskfile`` variable, but there is no way to specify content of the file, so there is no way to specify pre-shared secret (password). 

I find it valuable to create a variable that will contain the contents of the file pointed to by `` zabbix_agent_tlspskfile``. The content of the file should be build from PSK identity and PSK secret value. I think it is appropriate to use two different variables for that eg. ``zabbix_agent_tlspskfile_identify`` and ``zabbix_agent_tlspskfile_secret``. 

In real use case the value of this variable will be defined as a constant or a value dynamically generated for each host through lookup. 

The PSK identify is 128 UTF-8 characters length string. The PSK secret value is 32 hexadecimal digits. Both of them can be generated by [password lookup](http://docs.ansible.com/ansible/latest/playbooks_lookups.html#the-password-lookup) in Ansible.

Without these changes, the possibility of using TLS-PSK in Zabbix agent installed throught  Ansible role is illusory.

**Comment by dj-wasabi** [comment]
Thank you for your explanation. I created a PR for this and have it merged.

**Comment by dj-wasabi** [comment]
This is part of the 1.0.0 release.

**Comment by ad-m** [comment]
@dj-wasabi , thank you!

**Comment by ad-m** [comment]
@dj-wasabi , what do you think about set default value of ``zabbix_agent_tlspsk_secret`` to ``"{{ lookup('password', 'credentials/' + ansible_hostname + '/zabbix_tlspsk chars=hexdigits length=64') }}"``? 

I think it is reasonable to set a random password by default. It will not be created if it is not used, so there should not be problems. On the other hand, if someone wants to use TLS-PSK it will have a strong, unique password for each server set up. This can be seen as a "[secure by default](https://en.wikipedia.org/wiki/Secure_by_default)" approach.

It looks like the [Ansible module also does not support TLS-PSK](http://docs.ansible.com/ansible/latest/zabbix_host_module.html) too (compare with http://www.zabbixbook.com/2016/09/23/how-to-set-host-encryption-parameters-via-the-api/ and https://www.zabbix.com/documentation/3.4/manual/api/reference/host/object#host for field ``tls_psk``). I will want to fix this and then I will come back here to make the appropriate changes. I would like the sample playbook to use the encrypted implementation without any effort. I believe it is possible.

I see no reason why encryption would not be running on every installation. I understand the cost of managing the CA, but this does not apply to simple passwords.

**Comment by ad-m** [comment]
See ansible/ansible#24248

**Comment by dj-wasabi** [comment]
Hi @ad-m 

I'm not sure I can force this in the role, it seems to me this is user/company specific. Don't get me wrong I'm all for encryption/ssl on all services, but not everyone is into this. 

When the Zabbix Puppet module (voxpopuli/zabbix) was still "under my command" I created some wiki pages with documentation for certain setups, because not everything can be documented in the readme file. Maybe it is an idea to just document (or just in the readme) in how to configure a secure Zabbix (Agent) installation/setup with the roles for those who want to use it.

The "PSK" setup is handled, but the role should also do something with certificates and like the creation of the PSK file, the role should also place these kinds of certificates on the host.  

I recreated a PR a while ago https://github.com/ansible/ansible/pull/28692 (Originally from beginning of this year, but it takes ages to get PR's merged at Ansible) to also configure TLS settings via API. There is a freeze now, so it takes at least a month to get it merged ....

If you have ideas or PR's in this secure setup documentation/setup, please let me know and will happily take a look at it/merge it.

**Comment by ad-m** [comment]
@dj-wasabi , i agree with you that encryption does not have to be enforced. That's why I would like to develop an example playbook when Ansible maintainer make changes to the appropriate Ansible module. I would like this playbook to be published in addition to the current (https://github.com/dj-wasabi/ansible-zabbix-agent#example-playbook). Now I'm waiting for changes in the Ansible module.

I fully understand that encryption is not for everyone. Currently I do not even use Zabbix management through Ansible, because I have configured automatic host registrations, which was sufficient. Other people may also not want to take advantage of automatic management through Ansible.

However, I see no reason why the default value of ``zabbix_agent_tlspsk_secret`` could not be set for people who would want to use encryption at all.
